services:
    bsrstarter:
        depends_on:
            - server
        build:
            context: services/bsr_starter_service
            target: bsrstarter
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
            - net
        volumes:
            - ./services/bsr_starter_service:/src:rw
    dataimporter:
        build:
            context: services/dataimporter_service
            target: dataimporter
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
            - net
        volumes:
            - ./services/dataimporter_service:/src:rw
        env_file: .env
        expose:
            - "$DATA_IMPORTER_PORT"
        ports:
            - "$DATA_IMPORTER_PORT:$DATA_IMPORTER_PORT"
    proxies:
        build:
            context: services/proxies_service
            target: proxies_manager
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
            - net
        volumes:
            - ./services/proxies_service:/src:rw
        env_file: .env
        expose:
            - "$PROXIES_PORT"
        ports:
            - "$PROXIES_PORT:$PROXIES_PORT"
    s3:
        build:
            context: services/s3_service
            target: s3
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
            - net
        volumes:
            - ./services/s3_service:/src:rw
        env_file: .env
        expose:
            - "$S3_PORT"
        ports:
            - "$S3_PORT:$S3_PORT"
    google_upload:
        depends_on:
            - server
        build:
            context: services/google_upload_service
            target: google_upload
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
            - net
        volumes:
            - ./services/google_upload_service:/src:rw
        env_file: .env
    s3_upload:
        depends_on:
            - server
        build:
            context: services/s3_upload_service
            target: s3_upload
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
            - net
        volumes:
            - ./services/s3_upload_service:/src:rw
        env_file: .env
    server:
        build:
            context: services/server_service
            target: server
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
            - net
        volumes:
            - ./services/server_service:/src:rw
        env_file: .env
        expose:
            - "$SERVER_PORT"
        ports:
            - "$SERVER_PORT:$SERVER_PORT"
        command:
            - "--workers"
            - "2"
            - "--preload"
            - "--worker-class=uvicorn.workers.UvicornWorker"
            - "-b"
            - "0.0.0.0:$SERVER_PORT"
    sellercentral_loader:
        build:
            context: services/sellercentral_loader
            target: server
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
            - net
        volumes:
            - ./services/sellercentral_loader:/src:rw
        env_file: .env
        expose:
            - "$SELLERCENTRAL_PORT"
        ports:
            - "$SELLERCENTRAL_PORT:$SELLERCENTRAL_PORT"
        command:
            - "--preload"
            - "--worker-class=uvicorn.workers.UvicornWorker"
            - "-b"
            - "0.0.0.0:$SELLERCENTRAL_PORT"
    web:
        depends_on:
            - server
        build:
            context: services/web
            target: web
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
            - net
        volumes:
            - ./services/web:/src:rw
        env_file: .env
        expose:
            - "$WEB_PORT"
        ports:
            - "$WEB_PORT:$WEB_PORT"
        command:
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "$WEB_PORT"
#    capsolver:
#        build:
#            context: ./captcha_service
#            target: capsolver
#            dockerfile: Dockerfile
#        restart: unless-stopped
#        networks:
#            - net
#        volumes:
#            - ./services/captcha_service:/src:rw
#        expose:
#            - "$CAPTCHA_PORT"
#        ports:
#            - "$CAPTCHA_PORT:$CAPTCHA_PORT"
networks:
    net:
        driver: bridge
