services:
    bsrstarter:
        build:
            context: ./bsr_starter_service
            target: bsrstarter
            dockerfile: Dockerfile
        restart: always
        networks:
            - net
        volumes:
            - ./bsr_starter_service:/app:rw
    dataimporter:
        build:
            context: ./dataimporter_service
            target: dataimporter
            dockerfile: Dockerfile
        restart: always
        networks:
            - net
        volumes:
            - ./dataimporter_service:/app:rw
        env_file: dataimporter.env
        ports:
            - "8831:8831"
    proxies:
        build:
            context: ./proxies_service
            target: proxies_manager
            dockerfile: Dockerfile
        restart: always
        networks:
            - net
        volumes:
            - ./proxies_service:/app:rw
        env_file: proxies_manager.env
        ports:
            - "8833:8833"
#    capsolver:
#        build:
#            context: ./captcha_service
#            target: capsolver
#            dockerfile: Dockerfile
#        restart: always
#        networks:
#            - net
networks:
    net:
        driver: bridge