services:
    bsrstarter:
        build:
            context: ./bsr_starter_service
            target: bsrstarter
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
            - net
        volumes:
            - ./bsr_starter_service:/src:rw
    dataimporter:
        build:
            context: ./dataimporter_service
            target: dataimporter
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
            - net
        volumes:
            - ./dataimporter_service:/src:rw
        env_file: .env
        ports:
            - "8831:8831"
    proxies:
        build:
            context: ./proxies_service
            target: proxies_manager
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
            - net
        volumes:
            - ./proxies_service:/src:rw
        env_file: .env
        ports:
            - "8833:8833"
    s3:
        build:
            context: ./s3_service
            target: s3
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
            - net
        volumes:
            - ./s3_service:/src:rw
        env_file: .env
        ports:
            - "8836:8836"
    google_upload:
        build:
            context: ./google_upload_service
            target: google_upload
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
            - net
        volumes:
            - ./google_upload_service:/src:rw
        env_file: .env
    server:
        build:
            context: ./server_service
            target: server
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
            - net
        volumes:
            - ./server_service:/src:rw
        env_file: .env
        ports:
            - "8832:8832"
    web:
        build:
            context: ./web
            target: web
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
            - net
        volumes:
            - ./web:/src:rw
        env_file: .env
        ports:
            - "8838:8838"
#    capsolver:
#        build:
#            context: ./captcha_service
#            target: capsolver
#            dockerfile: Dockerfile
#        restart: unless-stopped
#        networks:
#            - net
#        volumes:
#            - ./web:/src:rw
networks:
    net:
        driver: bridge
